services:
  vite-front-bootstrap:
    container_name: vite-front-bootstrap-dev
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5171:5173"